version: '3.8'

services:
  app:
    build: .
    container_name: keuangan_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: keuangan
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"